### ISSUE TITLE
Panic when changing the volume of a device/output and using pipewire-pulse

### ISSUE THREAD

**Issue by danyspin97** [VixenUtils/Myxer#6]
[Full backtrace](https://gist.github.com/DanySpin97/afae07dc2c252e895e3a319a3a2208a3).
Tested with pulseeffects-5.0.3 and pipewire-0.3.25.

**Comment by Aurailus** [comment]
This one is curious. I'll have to look into it.

**Comment by guihkx** [comment]
Couldn't reproduce this with pipewire-pulse 0.3.26.

**Comment by ibrokemypie** [comment]
Getting the same thing here on arch, pipewire-pulse version 1:0.3.30-2, myxer version 1.2.1-1

**Comment by DanySpin97** [comment]
I have worked a bit on this issue. The problem is that the rust pulse bindings don't expect that `pa_context_set_volume_by_index` returns a NULL pointer. It only happens with PulseEffects open, so it's not possible to actually try with pulseaudio.

My guess is that either pipewire is behaving differently than pulseaudio or the state of Myxer is not correct. I don't have enough knowledge on either though.

**Comment by Aurailus** [comment]
Thanks for the research! It sounds like it's either an issue with pipewire or libpulse_binding, then?
If so, it would be best to open an issue there about the root cause, which is the NULL pointer.
Thanks!

**Comment by danyspin97** [comment]
This bug is not happening anymore with EasyEffects, I am closing this bug.
